title: Stackbit Agency Theme
baseURL: /
ignoreErrors: ["error-disable-taxonomy"]
taxonomies:
  category: categories
  tag: tags
  author: authors
disableKinds:
  - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
